CREATE OR REPLACE FUNCTION trigg_funct_clean_data()
RETURNS TRIGGER
LANGUAGE PLPGSQL AS
$BODY$
DECLARE

	V_POPULATION VARCHAR;
	V_YEARLY_CHANGE VARCHAR;
	V_NET_CHANGE VARCHAR;
	V_DENSITY VARCHAR;
	V_LAND_AREA VARCHAR;
	V_MIGRANTS VARCHAR;
	V_FERT_RATE VARCHAR;
	V_MED_AGE VARCHAR;
	V_URBAN_POP VARCHAR;
	V_WORLD_SHARE VARCHAR;
	B_AUTO_INSERT BOOLEAN;
BEGIN
	
	V_POPULATION = CAST(NEW.POPULATION AS VARCHAR);
	IF (POSITION('N.A.' IN V_POPULATION) > 0) THEN
		NEW.POPULATION = NULL;
	END IF;
	
	V_YEARLY_CHANGE = CAST(NEW.YEARLY_CHANGE AS VARCHAR);
	IF (POSITION('N.A.' IN V_YEARLY_CHANGE) > 0) THEN
		NEW.YEARLY_CHANGE = NULL;
	ELSIF (POSITION('%' IN V_YEARLY_CHANGE) > 0) THEN
		NEW.YEARLY_CHANGE = TRIM(REPLACE(V_YEARLY_CHANGE, '%',''));
		--YEARLY_CHANGE = CAST(TRIM(REPLACE(V_YEARLY_CHANGE, '%','')) AS NUMERIC);
		--YEARLY_CHANGE = YEARLY_CHANGE/100;
		--NEW.YEARLY_CHANGE = CAST(YEARLY_CHANGE AS VARCHAR);
	END IF;
	
	V_NET_CHANGE = CAST(NEW.NET_CHANGE AS VARCHAR);					 
	IF (POSITION('N.A.' IN V_NET_CHANGE) > 0) THEN
		NEW.NET_CHANGE = NULL;
	END IF;

	V_DENSITY = CAST(NEW.DENSITY AS VARCHAR);					 
	IF (POSITION('N.A.' IN V_DENSITY) > 0) THEN
		NEW.DENSITY = NULL;
	END IF;
	
	V_LAND_AREA = CAST(NEW.LAND_AREA AS VARCHAR);						 
	IF (POSITION('N.A.' IN V_LAND_AREA) > 0) THEN
		NEW.LAND_AREA = NULL;
	END IF;
	
	V_MIGRANTS = CAST(NEW.MIGRANTS AS VARCHAR);				
	IF (POSITION('N.A.' IN V_MIGRANTS) > 0) THEN
		NEW.MIGRANTS = NULL;
	END IF;
	
	V_FERT_RATE = CAST(NEW.FERT_RATE AS VARCHAR);
	IF (POSITION('N.A.' IN V_FERT_RATE) > 0) THEN
		NEW.FERT_RATE = NULL;
	END IF;
	
	V_MED_AGE = CAST(NEW.MED_AGE AS VARCHAR);						 
	IF (POSITION('N.A.' IN V_MED_AGE) > 0) THEN
		NEW.MED_AGE = NULL;
	END IF;
	
	V_URBAN_POP = CAST(NEW.URBAN_POP AS VARCHAR);
	IF (POSITION('N.A.' IN V_URBAN_POP) > 0) THEN
		NEW.URBAN_POP = NULL;
	ELSIF (POSITION('%' IN V_URBAN_POP) > 0) THEN
		NEW.URBAN_POP = TRIM(REPLACE(V_URBAN_POP,'%',''));
		--URBAN_POP = CAST(TRIM(REPLACE(V_URBAN_POP,'%','')) AS NUMERIC);
		--URBAN_POP = URBAN_POP/100;
	END IF;
	
	V_WORLD_SHARE = CAST(NEW.WORLD_SHARE AS VARCHAR);
	IF (POSITION('N.A.' IN V_WORLD_SHARE) > 0) THEN
		NEW.WORLD_SHARE = NULL;
	ELSIF (POSITION('%' IN V_WORLD_SHARE) > 0) THEN
		NEW.WORLD_SHARE = TRIM(REPLACE(V_WORLD_SHARE, '%', ''));
		--WORLD_SHARE = CAST(TRIM(REPLACE(V_WORLD_SHARE, '%', '')) AS NUMERIC);
		--WORLD_SHARE = WORLD_SHARE/100;
		--NEW.WORLD_SHARE = CAST(WORLD_SHARE AS VARCHAR);
	END IF;
	
	RETURN NEW;
END;
$BODY$




